/**
 * hub-notification
 *
 * Copyright (C) 2017 Black Duck Software, Inc.
 * http://www.blackducksoftware.com/
 *
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Sat Jun 10 07:53:04 GMT 2017
 */

package com.blackducksoftware.notification.config;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.evosuite.runtime.sandbox.Sandbox;
import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;

@EvoSuiteClassExclude
public class JMSConfig_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "com.blackducksoftware.notification.config.JMSConfig"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "UTF-8"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("user.country", "US"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.timezone", "America/New_York"); 
    java.lang.System.setProperty("sun.management.compiler", "HotSpot 64-Bit Tiered Compilers"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(JMSConfig_ESTest_scaffolding.class.getClassLoader() ,
      "org.springframework.util.ReflectionUtils$FieldFilter",
      "com.google.gson.internal.bind.TimeTypeAdapter$1",
      "org.dozer.jmx.DozerStatisticsController",
      "org.springframework.jms.support.converter.SimpleMessageConverter",
      "org.dozer.DozerBeanMapper",
      "org.apache.activemq.blob.BlobDownloadStrategy",
      "org.apache.commons.lang3.StringUtils",
      "com.google.gson.GsonBuilder",
      "com.google.gson.internal.bind.JsonTreeWriter",
      "org.dozer.stats.StatisticsManagerImpl",
      "org.apache.activemq.state.CommandVisitor",
      "org.apache.activemq.ActiveMQPrefetchPolicy",
      "org.springframework.util.ConcurrentReferenceHashMap$Segment$1",
      "org.springframework.core.Constants",
      "com.google.gson.internal.bind.TimeTypeAdapter",
      "org.apache.activemq.management.StatsCapable",
      "org.springframework.jms.core.MessagePostProcessor",
      "org.springframework.util.ClassUtils",
      "org.apache.activemq.broker.region.policy.RedeliveryPolicyMap",
      "org.apache.activemq.ClientInternalExceptionListener",
      "org.apache.activemq.ActiveMQConnectionFactory",
      "com.google.gson.LongSerializationPolicy",
      "org.dozer.jmx.DozerStatisticsControllerMBean",
      "org.apache.activemq.ConnectionFailedException",
      "com.google.gson.internal.bind.TypeAdapters$35$1",
      "com.google.gson.internal.Excluder",
      "org.apache.activemq.thread.TaskRunnerFactory",
      "org.apache.activemq.command.DataStructure",
      "org.apache.activemq.blob.BlobTransferPolicy",
      "org.springframework.jms.core.SessionCallback",
      "com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter",
      "com.google.gson.internal.$Gson$Types",
      "org.apache.activemq.command.ActiveMQTempQueue",
      "org.springframework.jms.support.destination.JmsDestinationAccessor",
      "org.dozer.classmap.RelationshipType",
      "org.springframework.context.annotation.Scope",
      "org.springframework.util.ReflectionUtils$MethodCallback",
      "org.springframework.util.ConcurrentReferenceHashMap",
      "org.dozer.util.DozerProxyResolver",
      "org.dozer.cache.DozerCacheType",
      "com.google.gson.Gson$FutureTypeAdapter",
      "com.google.gson.internal.bind.TreeTypeAdapter",
      "com.google.gson.stream.JsonWriter",
      "org.springframework.jms.core.BrowserCallback",
      "com.google.gson.internal.bind.ArrayTypeAdapter$1",
      "org.apache.activemq.filter.DestinationMapNode",
      "org.springframework.util.ConcurrentReferenceHashMap$Entries",
      "org.apache.activemq.Closeable",
      "com.google.gson.internal.ObjectConstructor",
      "com.google.gson.JsonNull",
      "org.dozer.stats.StatisticType",
      "com.google.gson.LongSerializationPolicy$1",
      "com.google.gson.LongSerializationPolicy$2",
      "com.google.gson.JsonObject",
      "com.google.gson.Gson$6",
      "org.apache.activemq.util.URISupport$CompositeData",
      "org.springframework.jms.core.ProducerCallback",
      "org.apache.activemq.transport.TransportListener",
      "org.dozer.MappingException",
      "com.google.gson.Gson$2",
      "com.google.gson.Gson$3",
      "com.google.gson.internal.bind.ObjectTypeAdapter",
      "com.google.gson.Gson$4",
      "com.google.gson.Gson$5",
      "org.dozer.metadata.MappingMetadata",
      "com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter",
      "com.google.gson.Gson$1",
      "org.apache.activemq.management.JMSConnectionStatsImpl",
      "com.google.gson.Gson",
      "org.dozer.loader.api.BeanMappingBuilder",
      "com.google.gson.internal.bind.JsonAdapterAnnotationTypeAdapterFactory",
      "org.apache.activemq.transport.ResponseCallback",
      "org.springframework.core.NestedRuntimeException",
      "com.google.gson.internal.bind.ReflectiveTypeAdapterFactory",
      "org.apache.activemq.EnhancedConnection",
      "org.apache.activemq.command.ActiveMQDestination",
      "org.dozer.loader.xml.ElementReader",
      "com.google.gson.internal.Excluder$1",
      "com.google.gson.internal.bind.TypeAdapters$2",
      "com.google.gson.internal.bind.TypeAdapters$1",
      "com.google.gson.JsonIOException",
      "com.google.gson.internal.bind.TypeAdapters$8",
      "org.apache.activemq.filter.DestinationMap",
      "com.google.gson.internal.bind.TypeAdapters$7",
      "com.google.gson.internal.bind.TypeAdapters",
      "com.google.gson.internal.bind.TypeAdapters$9",
      "org.apache.activemq.util.ClassLoadingAwareObjectInputStream",
      "com.google.gson.internal.bind.TypeAdapters$4",
      "org.apache.commons.logging.impl.Jdk14Logger",
      "com.google.gson.internal.bind.TypeAdapters$3",
      "com.google.gson.internal.bind.TypeAdapters$6",
      "org.apache.activemq.blob.BlobUploadStrategy",
      "com.google.gson.internal.bind.TypeAdapters$5",
      "com.blackducksoftware.notification.config.JMSConfig",
      "com.google.gson.FieldNamingPolicy",
      "com.google.gson.internal.bind.CollectionTypeAdapterFactory",
      "org.apache.activemq.util.IntrospectionSupport",
      "org.apache.activemq.management.StatisticImpl",
      "org.dozer.cache.CacheManager",
      "org.dozer.cache.DozerCache$LRUMap",
      "org.springframework.jms.core.JmsTemplate",
      "com.google.gson.JsonPrimitive",
      "org.apache.activemq.util.URISupport",
      "org.dozer.jmx.DozerAdminControllerMBean",
      "org.apache.activemq.command.Command",
      "com.google.gson.JsonSyntaxException",
      "org.dozer.jmx.JMXPlatform",
      "org.dozer.DozerInitializer",
      "org.springframework.context.annotation.ScopedProxyMode",
      "org.apache.activemq.filter.DestinationMapEntry",
      "org.springframework.jms.support.JmsAccessor",
      "org.springframework.jms.core.MessageCreator",
      "org.springframework.util.ReflectionUtils",
      "org.springframework.util.Assert",
      "org.springframework.jms.core.JmsOperations",
      "org.dozer.factory.XMLBeanFactory",
      "com.google.gson.reflect.TypeToken",
      "org.dozer.BeanFactory",
      "org.springframework.util.ReflectionUtils$FieldCallback",
      "org.apache.activemq.ActiveMQConnectionFactory$3",
      "com.google.gson.internal.bind.TypeAdapters$23",
      "org.apache.activemq.ActiveMQConnectionFactory$2",
      "com.google.gson.internal.bind.TypeAdapters$24",
      "org.apache.activemq.ActiveMQConnectionFactory$1",
      "com.google.gson.internal.bind.TypeAdapters$25",
      "com.google.gson.internal.bind.TypeAdapters$26",
      "com.google.gson.internal.bind.TypeAdapters$20",
      "com.google.gson.TypeAdapter",
      "com.google.gson.internal.bind.TypeAdapters$21",
      "org.dozer.util.DozerClassLoader",
      "org.springframework.cloud.context.config.annotation.RefreshScope",
      "com.google.gson.internal.bind.TypeAdapters$22",
      "org.dozer.util.MappingUtils",
      "com.google.gson.internal.bind.TypeAdapters$27",
      "com.google.gson.FieldNamingStrategy",
      "com.google.gson.internal.bind.TypeAdapters$28",
      "com.google.gson.internal.bind.TypeAdapters$29",
      "com.google.gson.internal.bind.SqlDateTypeAdapter",
      "org.springframework.jms.connection.ConnectionFactoryUtils$ResourceFactory",
      "com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper",
      "org.springframework.jms.JmsException",
      "org.springframework.jms.support.destination.DynamicDestinationResolver",
      "com.google.gson.internal.bind.TypeAdapters$34",
      "com.google.gson.internal.bind.TypeAdapters$35",
      "org.dozer.util.DefaultProxyResolver",
      "org.apache.activemq.management.StatsImpl",
      "com.google.gson.internal.bind.TypeAdapters$30",
      "org.apache.activemq.management.Resettable",
      "com.google.gson.internal.bind.TypeAdapters$32",
      "com.google.gson.internal.bind.TypeAdapters$33",
      "com.google.gson.JsonArray",
      "org.dozer.loader.xml.SimpleElementReader",
      "org.dozer.DozerModule",
      "org.springframework.jms.support.converter.MessageConverter",
      "org.springframework.util.ConcurrentReferenceHashMap$Task",
      "com.google.gson.TypeAdapterFactory",
      "com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter",
      "org.dozer.stats.StatisticsManager",
      "org.apache.activemq.jndi.JNDIStorableInterface",
      "com.google.gson.stream.JsonReader",
      "org.springframework.util.ConcurrentReferenceHashMap$ReferenceManager",
      "org.springframework.util.ConcurrentReferenceHashMap$ReferenceType",
      "com.google.gson.internal.bind.MapTypeAdapterFactory",
      "org.springframework.util.ConcurrentReferenceHashMap$1",
      "org.springframework.util.ConcurrentReferenceHashMap$2",
      "org.springframework.util.ConcurrentReferenceHashMap$3",
      "org.springframework.util.ConcurrentReferenceHashMap$4",
      "com.google.gson.internal.bind.TypeAdapters$12",
      "com.google.gson.internal.bind.TypeAdapters$13",
      "com.google.gson.internal.bind.TypeAdapters$14",
      "com.google.gson.internal.bind.TypeAdapters$15",
      "com.google.gson.internal.bind.TypeAdapters$10",
      "com.google.gson.internal.bind.TypeAdapters$11",
      "org.apache.activemq.ActiveMQDispatcher",
      "com.google.gson.stream.MalformedJsonException",
      "com.google.gson.internal.bind.ArrayTypeAdapter",
      "org.dozer.cache.DozerCache",
      "org.springframework.util.ReflectionUtils$MethodFilter",
      "com.google.gson.internal.bind.TypeAdapters$16",
      "com.google.gson.internal.bind.TypeAdapters$17",
      "com.google.gson.internal.bind.TypeAdapters$18",
      "com.google.gson.internal.bind.TypeAdapters$19",
      "com.google.gson.internal.bind.DateTypeAdapter$1",
      "org.dozer.util.DozerConstants",
      "org.springframework.util.ConcurrentReferenceHashMap$5",
      "com.google.gson.TypeAdapter$1",
      "org.springframework.util.ConcurrentReferenceHashMap$Reference",
      "org.apache.activemq.command.ActiveMQTempDestination",
      "org.apache.activemq.management.JMSStatsImpl",
      "org.springframework.util.ConcurrentReferenceHashMap$Segment",
      "com.google.gson.internal.bind.DateTypeAdapter",
      "org.dozer.jmx.JMXPlatformImpl",
      "org.apache.activemq.jndi.JNDIBaseStorable",
      "com.google.gson.internal.bind.TypeAdapters$26$1",
      "org.springframework.util.ReflectionUtils$4",
      "org.springframework.util.ReflectionUtils$6",
      "org.springframework.util.ReflectionUtils$5",
      "org.dozer.jmx.DozerAdminController",
      "org.apache.activemq.ConnectionClosedException",
      "com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$BoundField",
      "com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1",
      "org.apache.activemq.MessageTransformer",
      "org.apache.activemq.ActiveMQConnection",
      "org.springframework.context.annotation.Configuration",
      "org.apache.activemq.filter.DestinationNode",
      "org.apache.activemq.command.ActiveMQTopic",
      "org.dozer.CustomFieldMapper",
      "com.google.gson.internal.bind.JsonTreeReader",
      "com.google.gson.internal.bind.SqlDateTypeAdapter$1",
      "org.dozer.config.BeanContainer",
      "org.dozer.cache.DozerCacheManager",
      "com.google.gson.internal.LazilyParsedNumber",
      "com.google.gson.internal.bind.ObjectTypeAdapter$1",
      "org.springframework.core.ConstantException",
      "com.google.gson.JsonParseException",
      "org.dozer.Mapper",
      "com.google.gson.internal.ConstructorConstructor",
      "com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter",
      "org.dozer.cache.Cache",
      "org.apache.activemq.RedeliveryPolicy",
      "org.apache.activemq.command.ActiveMQQueue",
      "org.apache.activemq.command.ActiveMQTempTopic",
      "org.apache.activemq.Service",
      "org.dozer.stats.GlobalStatistics",
      "org.springframework.beans.factory.InitializingBean",
      "org.apache.commons.lang3.CharSequenceUtils",
      "com.google.gson.JsonElement",
      "org.dozer.util.ResourceLoader",
      "org.springframework.jms.support.converter.MessageConversionException",
      "org.apache.activemq.ConfigurationException",
      "org.springframework.jms.support.destination.DestinationResolver",
      "org.dozer.util.DefaultClassLoader",
      "org.springframework.jms.core.JmsTemplate$JmsTemplateResourceFactory",
      "com.google.gson.FieldNamingPolicy$4",
      "com.google.gson.FieldNamingPolicy$3",
      "org.springframework.stereotype.Component",
      "com.google.gson.FieldNamingPolicy$5",
      "org.dozer.config.GlobalSettings",
      "com.google.gson.FieldNamingPolicy$2",
      "com.google.gson.FieldNamingPolicy$1"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(JMSConfig_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "com.blackducksoftware.notification.config.JMSConfig",
      "org.springframework.context.annotation.ScopedProxyMode",
      "org.springframework.beans.factory.annotation.Autowire",
      "org.apache.activemq.jndi.JNDIBaseStorable",
      "org.apache.activemq.ActiveMQConnectionFactory",
      "org.apache.activemq.ActiveMQPrefetchPolicy",
      "org.apache.activemq.filter.DestinationMap",
      "org.apache.activemq.filter.DestinationMapNode",
      "org.apache.activemq.RedeliveryPolicy",
      "org.apache.activemq.ActiveMQConnection",
      "org.apache.activemq.util.ClassLoadingAwareObjectInputStream",
      "org.apache.activemq.util.IntrospectionSupport",
      "org.springframework.util.ConcurrentReferenceHashMap$ReferenceType",
      "org.springframework.util.ConcurrentReferenceHashMap",
      "org.springframework.util.ConcurrentReferenceHashMap$Segment",
      "org.springframework.util.ReflectionUtils",
      "org.springframework.jms.support.JmsAccessor",
      "org.springframework.jms.support.destination.JmsDestinationAccessor",
      "org.springframework.util.ClassUtils",
      "org.springframework.jms.core.JmsTemplate",
      "org.apache.commons.logging.impl.Jdk14Logger",
      "org.dozer.classmap.RelationshipType",
      "org.dozer.util.DozerConstants",
      "org.dozer.config.BeanContainer",
      "org.apache.commons.lang3.StringUtils",
      "org.apache.commons.lang3.CharSequenceUtils",
      "org.dozer.config.GlobalSettings",
      "org.dozer.stats.GlobalStatistics",
      "org.dozer.DozerInitializer",
      "org.dozer.cache.DozerCacheType",
      "org.dozer.cache.DozerCache$LRUMap",
      "org.dozer.stats.StatisticType",
      "com.google.gson.internal.Excluder",
      "com.google.gson.LongSerializationPolicy$1",
      "com.google.gson.LongSerializationPolicy$2",
      "com.google.gson.LongSerializationPolicy",
      "com.google.gson.FieldNamingPolicy$1",
      "com.google.gson.FieldNamingPolicy$2",
      "com.google.gson.FieldNamingPolicy$3",
      "com.google.gson.FieldNamingPolicy$4",
      "com.google.gson.FieldNamingPolicy$5",
      "com.google.gson.FieldNamingPolicy",
      "com.google.gson.internal.$Gson$Types",
      "com.google.gson.Gson",
      "com.google.gson.internal.bind.TypeAdapters$27",
      "com.google.gson.internal.bind.TypeAdapters",
      "com.google.gson.internal.bind.ObjectTypeAdapter",
      "com.google.gson.internal.bind.DateTypeAdapter",
      "com.google.gson.internal.bind.TimeTypeAdapter",
      "com.google.gson.internal.bind.SqlDateTypeAdapter",
      "com.google.gson.internal.bind.ArrayTypeAdapter"
    );
  }
}
