#  common configuration section
spring:
  profiles.active: local
---
hub:
    username: sysadmin
    password: blackduck
    timeout: 120000
    serverurl: http://eng-hub-verify01.dc1.lan
    cronExpression: 0 0/2 * 1/1 * *
    
spring:
    batch.job.enabled: false
    cloud.config.server.git.uri: /refresh-config
    activemq.broker-url: vm://localhost:61616
    activemq.user: admin
    activemq.password: admin    

server:
    port: 0
---
#  development configuration section 0 0/1 * * * *
spring:
    profiles: development
---
#  integration configuration section
spring:
    profiles: integration
---
#  qa configuration section
spring:
    profiles: qa
---
#  staging configuration section
spring:
    profiles: staging
---
#  demo configuration section
spring:
    profiles: demo
---
#  production configuration section
spring:
    profiles: production