/**
 * hub-notification
 *
 * Copyright (C) 2017 Black Duck Software, Inc.
 * http://www.blackducksoftware.com/
 *
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
/*
 * This file was automatically generated by EvoSuite
 * Sat Jun 10 07:52:48 GMT 2017
 */

package com.blackducksoftware.notification.batch.processor;

import static org.evosuite.runtime.EvoAssertions.verifyException;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.fail;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.batch.core.BatchStatus;
import org.springframework.batch.core.JobExecution;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false, useJEE = true) 
public class JobCompletionNotificationListener_ESTest extends JobCompletionNotificationListener_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      JobCompletionNotificationListener jobCompletionNotificationListener0 = new JobCompletionNotificationListener();
      // Undeclared exception!
      try { 
        jobCompletionNotificationListener0.afterJob((JobExecution) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.blackducksoftware.notification.batch.processor.JobCompletionNotificationListener", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      JobCompletionNotificationListener jobCompletionNotificationListener0 = new JobCompletionNotificationListener();
      Long long0 = new Long(0L);
      JobExecution jobExecution0 = new JobExecution(long0);
      BatchStatus batchStatus0 = BatchStatus.COMPLETED;
      jobExecution0.setStatus(batchStatus0);
      jobCompletionNotificationListener0.afterJob(jobExecution0);
      assertEquals(BatchStatus.COMPLETED, jobExecution0.getStatus());
  }
}
